### ISSUE TITLE
Overlapping markers

### ISSUE THREAD

**Issue by j16h** [mapbox/mapbox.js#1009]
I faced with an issue when I have more than 10 markers that staying at the same position (lat, lng) - they are overlapped. I've googled for solution and found the one -https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet

Would be nice to have it as a part of mapbox api.

Or if there are other solutions how to solve such issue, I would be more than happy to hear.

Thanks

**Comment by tmcw** [comment]
Hey Julian,

Sure - you can use the spiderfier plugin or [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) with Mapbox.js. We even [provide a CDN so that you can include them without downloading the libraries](https://www.mapbox.com/mapbox.js/plugins/).

Our approach with plugins is the same as Leaflet's: they're great ways that you can extend functionality on a case-by-case basis. We don't include them in the bundle because it's include a lot of code that's necessary for some users but unnecessary for others - we'd rather have a great core of functionality and let add-ons be opt-in.

**Comment by j16h** [comment]
Thank you!!!
