### ISSUE TITLE
Popups no longer function after filtering markers in mapbox

### ISSUE THREAD

**Issue by j16h** [mapbox/mapbox.js#1016]
I have customized popup, when apply the filter on the markers, the custom popup is no longer exist, instead of custom popup it shows default popup.

**Comment by lyzidiamond** [comment]
Hi @julianusti! Are you using `setFilter()` to do the filtering? Can you post your code so I can take a look?

**Comment by j16h** [comment]
Hi @lyzidiamond,
Yes, I use `setFilter()` function.

```
function handleSearch(name) {
    let searchingName = name.toLowerCase();

    let showDriver = (feature) => {
      return feature.properties.name
        .toLowerCase()
        .indexOf(searchingName) !== -1;
    };

    driversLayer.setFilter(showDriver);
  }
```

**Comment by j16h** [comment]
Hi @lyzidiamond,

Is there are any updates? 

Thanks,
Julian

**Comment by lyzidiamond** [comment]
When you use `.setFilter()`, your features are being removed and re-added. This means whatever you added to your features before you filtered will be removed when they're readded.

You can get around this by adding popups to your features on layer add:

`map.on('layeradd', function(layer) { ... });`

Hope that helps!

**Comment by j16h** [comment]
Hi @lyzidiamond,
Could it be done in a more user-friendly way?

Whenever `.setFilter()` is called, we have to take a look if the marker has a custom popup and persisting this part of information, so it could be added later on when the marker is added back.

**Comment by tmcw** [comment]
@julianusti that would be a very incomplete solution: you can call setFilter multiple times, and it'd be easy to call `setFilter(function() { return false; })` and then `setFilter(function() { return true; })` and blow away all tooltips.

The solution to this is what @lyzidiamond laid out before - popups are best implemented on layeradd rather than with eachLayer - that way they also work properly with calls like `setGeoJSON`.
