### ISSUE TITLE
Map users want a scale on the map

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox.js#1047]
This has been a recurring help issue on Mapbox maps from the start:

> - Maps need a legend/scale with miles/kilometers to help judge distance, e.g., if one needs to walk from point A to point B it is difficult to tell distances w/o a scale on the map
> - A scalable scale with standard and metric units
> - a scale is missing on this map. How big is Syria? 1km², 1000000km²? i can't tell.
> - There is no scale on the interactive map. Or I'm not seeing it - but there is no line that says '1 cm = 5 km' or '1:1000' etc. Would be helpful in judging distances.
> - You need to add a bar scale for estimating distances, or better a drag tool that would display the distance from point a to point b
> - There is no scale on this map. This means that it is a picture, not a map!
> - So, when looking at a potential housing location, there is no way to tell if you're 2 miles from the nearest grocery store, or 20 miles?
>   -Include a scale/time table so we can accurately measure distances on our trip. It would greatly help with planning which hotel to book.
> - A scale and a measurement tool would be useful for comparison with nearby locations
> - There is no scale for estimating distances between two points.

There is enough points of feedback to seriously consider add the [scale control](https://www.mapbox.com/mapbox.js/example/v1.0.0/scale-control/) to the map by default instead of leaving it upto the developer to enable.

Measuring distances on a map is a basic user need and without a scale or a directions widget there is no way for a user to do this on Mapbox maps.

cc @mourner @tmcw @tatsvc @lxbarth

**Comment by tmcw** [comment]
I strongly disagree:
- All of these seem to be from third-party sites
- Turning a UI control on would require a major version bump and would lead to lots of people asking "how do I turn the scale off"
- Scales are the wrong way to tell the distance between locations: use directions
- Scales are the wrong way to tell how big countries are: use wikipedia
- The lack of a scale does not make a map a picture: this is something a pedant says

Developers can add the scale to these third-party sites if they want to.

Mapbox.js should, as it has in the past, kept optional features off by default rather than cluttering itself by trying to appease all users. Scales on maps are useful, potentially, for map portals, or for people with stubborn expectations. Our users are not all those people and the places our maps are used vary, from tiny tiny thumbnails to pure visualizations. Let's keep the defaults only to those that are really necessary.

**Comment by planemad** [comment]
@tmcw this is the first map UX related issue that has seen significant volume in our feedback system. Its a good test case to figure out how to handle such types of feedbacks in a consistent way.

Going by the past trend there will continue to be requests for a distance/scale tool. Till what point will we consider such a user need as unnecessary?

**Comment by tmcw** [comment]
> Going by the past trend there will continue to be requests for a distance/scale tool. Till what point will we consider such a use need as unnecessary?

This is not the right way to look at it:

First off, I don't see any usecases as unnecessary. The decision for whether something is included in core and/or enabled by default is based on _universality_: do 99% of our maps need this?
- Map: yes, we need this
- Attribution: legally, we need this
- Map Controls: yes, because not all users have/use scrollwheels

As far as a legend: should maps on Pinterest have a legend? On Foursquare? In map thumbnails in Strava? I'd wager "no".

---

Since all of the feedback is coming in through the "improve this map" link on external sites, the task is communicating this feature request to those third-party sites, and dropping a code snippet of the extremely simple one-line way to add a scale to the map:

``` js
L.control.scale().addTo(map);
```

**Comment by lyzidiamond** [comment]
@planemad thanks for bringing this up! It's always good to be thinking about our users and what they want to see.

In the case of the scalebar, I agree with @tmcw that it's not something that should appear on our maps by default, for a couple reasons:
- putting real-world scale on a web mercator map is confusing and generally a bad idea. Literally every time you pan the map, even a little bit, the scale bar changes. Take a look at the Mapbox.js example to see what I mean: https://www.mapbox.com/mapbox.js/example/v1.0.0/scale-control/
- keeping things minimal in terms of what shows up by default saves a lot of support time -- if we add something not everyone wants, people will be constantly wondering how to turn it off
- It is one line of JavaScript to add it in, as @tmcw demonstrated above

To your other point, though, we should definitely come up with a way for this feedback to funnel back to the developers who are building these maps. This is a cool service we can provide for our users, and something I think they would appreciate greatly!

@planemad do you know if we currently have any processes in place that are doing this currently? We can also continue this conversation in [map-feedback](/mapbox/map-feedback/) if that makes more sense.

**Comment by planemad** [comment]
Thanks @tmcw and @lyzidiamond for your views. If the consensus is that a distance measuring tool is not a universal map requirement, lets close this for now.

@lyzidiamond  let continue this on map-feedback.
