### ISSUE TITLE
Can't load map by username.id

### ISSUE THREAD

**Issue by Sequoia** [mapbox/mapbox.js#1147]
https://www.mapbox.com/mapbox.js/api/v2.4.0/l-mapbox-map/ `.map` method takes `id|url|tilejson` as argument number 2.

I created a "style" on mapbox, copied my tokens etc. over, but when I try to load my style I get a 404.
## Works

`var map = L.mapbox.map(mapElemId, 'mapbox.streets')`
## Doesn't work

`var map = L.mapbox.map(mapElemId, 'sequoia123.default-map-sequoia')`

I can't find anywhere on the website to create a "map." Where do I find this "map id?"

**Comment by tmcw** [comment]
Hi Sequoia!

That's a new style that you created, with the title `default-map-sequoia`. To use it with Mapbox.js, you can click on the "Share & use" option to the right of the layer in Mapbox Studio, which will bring you to the share page. In the center column, there's the Style URL you'll use (which is `mapbox://styles/sequoia123/ciolxhmk80000atmd1raqh0rs`), and using that with `L.mapbox.styleLayer` should work perfectly!

**Comment by Sequoia** [comment]
Where do "map IDs" come from? If I wanted to create a "map" how would I do that?

Thanks!

**Comment by Sequoia** [comment]
So you can use a style-layer in lieu of  a tileset?

**Comment by tmcw** [comment]
Sure, so:
- map ids are from TileMill, Mapbox Studio Classic, and Mapbox Editor projects. They're ids for raster tiles that you create through one of those techniques, and they're part of our older tile API.
- style urls are from Mapbox Studio tiles. They're from the newer API, and by default are 512px tiles, rather than 256px across.

It's a bit confusing, unfortunately; we're working through another period of transition and hoping that things will be clearer in the future.

**Comment by tmcw** [comment]
Closing; feel free to comment if this hasn't been adequately explained.
