### ISSUE TITLE
Show/hide layers

### ISSUE THREAD

**Issue by redka** [mapbox/mapbox.js#1169]
I have one style with several layers which is made in MapBox Studio. I want to separately show and hide each of these layers using MapBox.js. Now I'm trying to do this placing each layer in separate styles and loading these styles as tileLayers. But I need to have all these layers to be inside one style. Is there any way to show and hide specific layers inside one style using MapBox.js?
On iOS using iOS SDK I can do this. I can pick specific layer from style using layer id and then change it's visibility.

**Comment by redka** [comment]
Now I use list styles: 
`let nullMap = L.tileLayer(mapUrl, {id: 'citmvgdpq000w2infbeg57gta', attribution: mapAttr}),
     trails = L.tileLayer(mapUrl, {id: 'citfglbr1007x2jp2ebg42ehq', attribution: mapAttr}),
     сautionaryOnStreet = L.tileLayer(mapUrl, {id: 'citzie82g00fp2irqsv8bsddm', attribution: mapAttr}),
     protectedBikeLanes = L.tileLayer(mapUrl, {id: 'citn7qlkl00062iqpzi04l3m6', attribution: mapAttr});`

I want change layer in one style. So in style change layers (review [image](https://pp.vk.me/c836128/v836128805/4064/60Q7ugxMU3Y.jpg) style with all layers https://pp.vk.me/c836128/v836128805/4064/60Q7ugxMU3Y.jpg)

**Comment by redka** [comment]
Now I use list styles: 
`let nullMap = L.tileLayer(mapUrl, {id: 'citmvgdpq000w2infbeg57gta', attribution: mapAttr}),
     trails = L.tileLayer(mapUrl, {id: 'citfglbr1007x2jp2ebg42ehq', attribution: mapAttr}),
     сautionaryOnStreet = L.tileLayer(mapUrl, {id: 'citzie82g00fp2irqsv8bsddm', attribution: mapAttr}),
     protectedBikeLanes = L.tileLayer(mapUrl, {id: 'citn7qlkl00062iqpzi04l3m6', attribution: mapAttr});`

I want change layer in one style. So in style change layers (review [image](https://pp.vk.me/c836128/v836128805/4064/60Q7ugxMU3Y.jpg) style with all layers https://pp.vk.me/c836128/v836128805/4064/60Q7ugxMU3Y.jpg)

**Comment by tmcw** [comment]
> Is there any way to show and hide specific layers inside one style using MapBox.js?

Currently, your way is the right way, but this would be much easier and more straightforward if you use [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/) instead of Mapbox.js. Mapbox.js is a traditional image-based map client, so it uses Mapbox's servers to turn your dynamic styles that pull in vector tiles into simple images that can be displayed. Mapbox GL JS, on the other hand, renders them on the client, which is the same thing that the iOS SDK is doing. Switching to GL JS will allow you do to exactly what you do with the iOS SDK, whereas any solution using Mapbox.js will be at most a workaround.
