### ISSUE TITLE
Mapbox popups not responsive

### ISSUE THREAD

**Issue by iamdriz** [mapbox/mapbox.js#1191]
When creating popups, I set the `minWidth` and `maxWidth` like so:
~~~
marker.bindPopup(html, {
  closeButton: true,
  closeOnClick: true,
  keepInView: true,
  minWidth: 280,
  maxWidth: window.innerWidth - 40,
  autoPanPadding: new L.Point(20, 20)
});
~~~

This then creates a popup with an actual width (inline CSS on `.leaflet-popup-content`).

However this only works on the initial load of your map and the creation of the popups. So if the user resizes their browser window the `maxWidth` does not update.

I'd consider this a bug because otherwise the only way to get this to work on smaller devices is to set the `maxWidth` to the lowest possible width of the device your map is going to be displayed on, meaning it will not use the available space when resized back to larger sizes.

Can the widths be made to be dynamic on `resize` as well `bindPopup`?

**Comment by tmcw** [comment]
Hi Cameron,

This is a valid usecase, but this isn't a bug: popup widths in Leaflet are meant to be _immutable_, which is a good thing: it simplifies the API to make these properties only settable in the initializer, rather than adding setter methods for each part of the popup. The deal with properties like that is that you can either:

**React to `resize` events by re-initializing the popups you previously bound.** This will, luckily, be faster than might be think, since you're only binding the 'data part' of the popup - it doesn't need to touch the DOM, which is the cause of most performance problems. If you move your popup binding to a method which you call initially and re-call on `window.resize`, this approach doesn't actually lead to much extra code.

``` js
function bindPopups() {
  marker.bindPopup(...);
}
bindPopups();
window.addEventListener('resize', bindPopups);
```

You can also react to marker clicks, which lets you use the window width at the time of click, rather than at initialization:

``` js
marker.on('click', function() {
  marker.bindPopup(html, {
  closeButton: true,
  closeOnClick: true,
  keepInView: true,
  minWidth: 280,
  maxWidth: window.innerWidth - 40,
  autoPanPadding: new L.Point(20, 20)
  }).openPopup();
});
```

Either of these solutions work well and are used in practice.
