### ISSUE TITLE
How to fitBounds for all visible features

### ISSUE THREAD

**Issue by sthomp** [mapbox/mapbox.js#1236]
I'd like to `fitBounds` for all features than can be visible on the map - regardless of if they are in the current viewport.

The use case is that after zooming into points on the map I'd like to press a button to zoom back out and fit all visible points. The visible points could be a subset of the original geojson points because I'm applying a filter to the layer.

**Comment by jfirebaugh** [comment]
Hi @sthomp, thanks for using Mapbox! There's no built-in facility for this in Mapbox.js, and since it's fairly application-specific, it's not likely something we'd add. You'll need to figure out how to calculate the appropriate bounds for the features you want visible, and then pass that to `fitBounds`.
