### ISSUE TITLE
Broken link on L.mapbox.tileLayer page

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/mapbox.js#1253]
The "Live example of .setFormat in use" link is broken on the [L.mapbox.tileLayer](https://www.mapbox.com/mapbox.js/api/v3.1.1/l-mapbox-tilelayer/) page.

**Comment by katydecorah** [comment]
I'm seeing an uptick of 404s to this example. We should remove the references to this page.

**Comment by katydecorah** [comment]
Looks like something is up with the redirects. 

* https://docs.mapbox.com/mapbox.js/example/v1.0.0/tilelayer-setformat/ is supposed to redirect to https://docs.mapbox.com/mapbox.js/example/v1.0.0/low-bandwidth/.
* https://docs.mapbox.com/mapbox.js/example/tilelayer-setformat/ redirects to https://docs.mapbox.com/mapbox.js/example/v1.0.0/low-bandwidth/.

I think the redirects folder is in the wrong location, but I'm not sure yet if that's intentional.

**Comment by katydecorah** [comment]
The fix would be to change the `categories: example` -> `categories: example/v1.0.0` in each redirect's frontmatter. 

I'm still unsure if the original category was set intentionally. I'll check the Sentry 404 logs to see the history of 404s for this site to see if there are any patterns.

I'm going to create a branch with this fix and push to staging to see what it looks like.

**Comment by katydecorah** [comment]
I'm not seeing any other redirect result in a 404 like /tilelayer-setformat/ is. I think it makes the most sense to update the old link paths for /tilelayer-setformat/ so that it can redirect properly - this will be lowest impact and would fix the original issue.
