### ISSUE TITLE
Zooming in on map breaks isochrone

### ISSUE THREAD

**Issue by iamwillow** [mapbox/mapbox.js#1342]
### Version:
"mapbox-gl": "^1.12.0",

### Bug:
When zooming in, the isochrone map UI breaks.  It looks like the  outline is still intact, but  the fill gets distorted.

### Zoomed out:
<img width="474" alt="Screen Shot 2020-11-24 at 09 10 29" src="https://user-images.githubusercontent.com/3923914/100105162-0bbcd080-2e35-11eb-917d-8be65906a087.png">

### Zoomed in:
<img width="628" alt="Screen Shot 2020-11-24 at 09 10 38" src="https://user-images.githubusercontent.com/3923914/100105198-137c7500-2e35-11eb-9c98-0e3daf45e4a8.png">

I circled the isochrone outline in red to show that it is still loading properly. Only the fill is broken.

### Isochrone Code: 
const fetchIsochrone = `https://api.mapbox.com/isochrone/v1/mapbox/${mapInfo.commuteType}/${dataLon},${dataLat}.json?contours_minutes=${mapInfo.commuteTime}&access_token=${MAPBOX_TOKEN}`;

Here is a copy of the isochrone data that gets returned with that API call:
[isochrone_data.txt](https://github.com/mapbox/mapbox.js/files/5590435/isochrone_data.txt)

```
map.on("load", function () {
    map.addSource("iso", {
        type: "geojson",
        data: fetchIsochrone,
    });
    map.addLayer({
        id: "isoLayer",
        type: "fill",
        source: "iso",
        layout: {},
        paint: {
            "fill-color": "#2557a7",
            "fill-opacity": 0.3,
        },
    }, "poi-label" ); 
});

**Comment by iamwillow** [comment]
Here is a copy of the isochrone data that the map is pulling in from the API.

[isochrone_data.txt](https://github.com/mapbox/mapbox.js/files/5590430/isochrone_data.txt)

**Comment by riastrad** [comment]
Thank you for using Mapbox! Based on the code snippet you've shared, it looks like you're using [Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/) rather than [Mapbox.js](https://docs.mapbox.com/mapbox.js). 

For general how-to questions like this, we recommend [contacting Mapbox Support](https://support.mapbox.com/hc/en-us) or asking on [Stack Overflow](https://stackoverflow.com/questions/tagged/mapbox+or+mapbox-gl-js+or+mapbox-gl+or+mapbox-android+or+mapbox-marker+or+mapbox-ios+or+mapbox-gl-draw+or+react-native-mapbox-gl+or+mapbox-static-maps+or+mapbox-unity+or+mapbox-studio+or+mapbox-plugin).
