### ISSUE TITLE
[Docs] Broken link to L.Mapbox.Template

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox.js#1347]
The link to L.Mapbox.Template is broken for the 3.3.1 docs. Looks like it *was* there in [3.3.0](https://github.com/mapbox/mapbox.js/blob/publisher-production/docs/_posts/api/v3.3.0/0200-01-01-l-mapbox-template.html). @riastrad do you know if this method was removed in 3.3.1?

**Comment by riastrad** [comment]
👋 @danswick the method is still available in 3.3.1. However, because it was tightly coupled with use of a legacy API that's soon to be EOL'd I removed mention of it in https://github.com/mapbox/mapbox.js/pull/1346. If I misunderstood the full potential of the method, then we can definitely add it back to the docs.

**Comment by danswick** [comment]
I don't have an opinion about keeping or dropping it, but there are still some links in the site's nav that should also be removed if the page is not coming back.
