### ISSUE TITLE
curated plugins

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#174]
http://leafletjs.com/plugins.html
- https://github.com/kartena/Leaflet.zoomslider
- https://github.com/Leaflet/Leaflet.draw
- https://github.com/Leaflet/Leaflet.markercluster

**Comment by mourner** [comment]
Bruno's draw is kind of outdated, better look at https://github.com/Leaflet/Leaflet.draw (branch 0.2, to be released in a couple of days).

I was going to take on improving zoomslider (both design and behavior, as it's not perfect) some day, maybe soon.

Markercluster is awesome.

**Comment by tmcw** [comment]
@mourner is there a viable plugin for KML? Looks like there's something in leaflet-plugins but no standalone project with activity.

**Comment by tmcw** [comment]
Adding to this list: http://sunng87.github.com/heatcanvas/leaflet.html - not perfect, maybe there's a better heatmap out there?

**Comment by mourner** [comment]
This one is much better: http://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html
Still not perfect though. One guy optimized the performance considerably but as a quick hack, didn't contribute back: http://heatmapdemo.alastair.is/
I was thinking about writing a high-quality heatmap plugin (loosely based on the previous works) myself, since I'll need it for a future project.

Regarding KML — there's no standalone plugin probably because KML sucks big time and no one sane is using it. :) Try the one from shramov's plugins, it may be good enough.

**Comment by tmcw** [comment]
-> https://github.com/mapbox/mapbox.js-plugins

**Comment by mourner** [comment]
@tmcw what's the end goal of the repo? Anything that could be adopted on the Leaflet side as well?
