### ISSUE TITLE
Improve leaflet inertia

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#209]
Feeling like Leaflet's intertia still needs some work. Low-priority but there's a bit of a difference between this and easey.MouseHandler

**Comment by mourner** [comment]
Yeah. I worked on it a lot for 0.5 — now the code behind it is much simpler, easier to understand and configure, but still needs tweaking — hard to get right.

The main difference from the technical side is that Leaflet uses CSS3 Transitions for the inertia, so it does its calculations very differently.

**Comment by jfirebaugh** [comment]
My feel is that the main weakness is not in the curve (that's close enough) but in the dragEnd -> CSS transition. One, [inertiaThreshold](https://github.com/Leaflet/Leaflet/blob/bf54caa1e9418b628a4c1264a3c9236e68fc9ba5/src/map/handler/Map.Drag.js#L11) is too low (should be more like 50), two, there's some jank at the beginning, either due to bad computations in L.Map.Drag or inherent in the initiation of the CSS transition.

**Comment by tmcw** [comment]
With @ansis's work here, we're set.
