### ISSUE TITLE
Documentation approach

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#281]
@ansis @jfirebaugh @heyitsgarrett 

Documentation approach!

![](http://www.lattix.com/files/images/technology/antuml.jpg)

So we have a host of issues:

**User confusion over what's mapbox.js and what's Leaflet**: beyond the `L` and `mapbox` divide - can users supply arguments from one to the other? Should we prefix everything? Should we prefix less? For instance, `mapbox.map('foo').setCenter(L.LatLng(blah))`

**Duplicated documentation? One source of documentation? Links?** Should we interlink docs? We'll want to, for instance, reference `LatLng` from our docs. Will this jump to leafletjs.com?

**Comment by heyitsgarrett** [comment]
One of things I found immediately confusing about current Mapbox.js 0.6.7 documentation was the use of MM.\* in some examples. I figured it out quickly, but it was a bit like seeing the wizard behind the curtain. I'm :+1: for prefixing everything `mapbox`. 

If we go with that prefix approach, being able to pass arguments to both `mapbox` and `L` seems a bit awkward, but we could quietly allow it..?

I also think we should own documentation with a sturdy asterisk at the top and bottom that points out the roots in Leaflet - we can certainly build a better-looking documentation, not to mention one that's more verbose and helpful.

**Comment by ansis** [comment]
I'm starting to think the mapbox stuff should be put under `L.mapbox`, and that mapbox.js should be considered a Leaflet plugin. A huge benefit of using Leaflet, both the code and name, is that we can say there is one API. Less confusion, less duplication of documentation.

Mapbox.js docs would cover the plugin's api, and would link to leafletjs.com which could be improved as necessary. The mapbox docs would still have examples and maybe a tutorial or two. Having everything under one site isn't that important, since basic users just want some examples to copy and paste, and advanced users will want to understand the relationship with Leaflet.

Having a duplicate copy of documentation and merging `L.*` into `mapbox` could work, but you don't get to take advantage of Leaflet's popularity. Its also not as clear what the relationship between mapbox.js and leaflet are. Is mapbox.js a fork? Whats different? Which should I use? Can I use Leaflet plugins?

I feel like the benefits of getting more behind the Leaflet name outweight the benefits of "forking" the name and docs.

**Comment by tmcw** [comment]
@ansis should we have `mapbox.map()` in that case - should overlapping functionality be removed? We would call this 'The MapBox Leaflet Plugin', or 'MapBox.js, a Leaflet Plugin', or 'MapBox.js for Leaflet'?

**Comment by ansis** [comment]
_MapBox.js for Leaflet_ or _Leaflet for MapBox_ could work. I'm just starting to look at the new mapbox.js, and I'm not really sure if this approach would work well. Just wanted to throw out the idea of trashing the wizard's curtain instead of making it a bit more opaque.

**Comment by tmcw** [comment]
Totally. We don't need to decide this right now, but I think you've got a good idea and we've just got to sort out how to communicate about what we choose etc.

**Comment by yhahn** [comment]
From an outside perspective: +1 `L.mapbox` -- I think the relationship implied by this is clear and easy to understand which always makes for an easier communications job.

**Comment by tmcw** [comment]
Okay, we're going to `L.mapbox`. Let's refactor this today.
