### ISSUE TITLE
Propose name changes

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#30]
These are upstream but I wanted to discuss them here:
### map

`layer.named -> layer.name`
Named in the past tense just seems weird - even for what it does.
### markers

`markers.factory` -> `markers.render`
factory to me is a pretty internal name. "Render" qualify's what it does: renders the object out as html
or re-renders them out

`markers.features  -> markers.data`
Features is such a geojson spec name. "data" seems like a more appropriate name for how we are using features.

`markers.addCallback -> markers.onEvent`
This feels more clear to me on some event specified in the first argument, do something (callback)

`markers.removeCallback -> markers.removeEvent`

`interaction.hide_on_move -> interaction.hideOnMove`
underscores just dont sit right with me .. we should camelCase right?

`interaction.formatter -> interaction.template`
Debatable change.
### ease

`ease.t -> ease.toPoint`
More clear

**Comment by tmcw** [comment]
Named needs to be named - modestmaps looks for `.name` as a property, and as such it can't be a function without very dangerous code, or a modestmaps tweak.

renderer could be valid, though it does refer to the [factory pattern](http://en.wikipedia.org/wiki/Factory_method_pattern)

markers.features refers to the `features` member of a GeoJSON feature collection, and markers.js aims to continue to support GeoJSON type objects internally, even if it supports other 'converters' to/from that format. `data` also could be confused with the `data` member in TileJSON.

`addCallback` and `removeCallback` are made to mirror modestmaps; I'd rather keep these continuous; they mirror addEventlistener in HTML and have been established for a while.

Hide on move, sure, works for me.

Template - no; this isn't templating, really: it doesn't take a template as an argument.

easey.toPoint I'd rather not use Point because it could be easily confused with MM.Point, which this has nothing to do with. open to other namings though

**Comment by tristen** [comment]
- Perhaps `setPosition` ? instead of toPoint ? 
- I know factory refers to the factory pattern but I feel like an api shouldn't bear its name - internally yes but not outwardly. the word, "render" attributes more closely to what it does I think.

**Comment by tmcw** [comment]
`render` is also a verb; you would expect `markers.render()` to render the markers. it would have to be `markers.renderer()` right?

**Comment by tristen** [comment]
Ah I see. Yes, renderer

**Comment by tmcw** [comment]
Technically it's like an `x` value in http://en.wikipedia.org/wiki/Interpolation . Position is also kind of an overloaded term; unless we can find something that's accurate and specific, I don't really want to change this (plus it's a pro feature anyway)

**Comment by tmcw** [comment]
We're supporting camelCase in v1 and such.
