### ISSUE TITLE
setView changes attribution status

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#308]
Diagnosis is: only when the map is 'ready' does it check to see if there are any layers that get `onAdd` called on them and trigger `layeradd`, and `layeradd` triggers an Attribution change.

**Comment by ansis** [comment]
Fixed in ce70810

This only covers loading via mapbox.map. Leaflet makes a bunch of assumptions about layers not changing after being added, so for this to be more thorough all that would need to change. It doesn't seem worth it to complicate leaflet when this fix covers the main case and isn't very intrusive.
