### ISSUE TITLE
url paths

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#326]
Right now I'm working on having a v1 version of the `/mapbox.js/` paths. @ansis brought up that we might want to just call it something else.

Open to ideas: time is running out though

![](http://25.media.tumblr.com/tumblr_m5dgduvoOE1rp83wgo1_400.gif)

**Comment by heyitsgarrett** [comment]
bettermapbox.js ;)

I like mapbox.js and if anything, we should make the switch to have mapbox.js default to v1 with legacy support at new URLs once it's completely ready for prime-time.

[Foundation](http://foundation.zurb.com/) just adds a number to theirs, which would make this mapbox.js 2 

[Bootstrap](http://twitter.github.io/bootstrap/) just rolls with it, noting the version below. I like this approach.

**Comment by ansis** [comment]
leaflet.mapbox.js is a possibility. Just like L.mapbox, it conveys the relationship with leaflet. It feels a bit odd calling it the same thing as v0, since its not a new version with some breaking changes. Everything breaks. Having different names might make it easier to communicate about the differences between v0 and v1.

**Comment by tmcw** [comment]
http://localhost:4000/mapbox.js/api/v1.0.0/ & http://localhost:4000/mapbox.js/example/v1.0.0/
