### ISSUE TITLE
Reimplement location formatter

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#335]
This was removed in 8181c14252890c5b95ebe800a2100a6d3523f10d by @jfirebaugh - it's reasonable on a security level, but we need to make notes and document when something like this is removed. This option is exposed in TileMill and implemented on MapBox.com and we can't simply drop it without notice.

I think we can sanitize this just fine with `html_sanitize`.

**Comment by jfirebaugh** [comment]
The way that this was exposed was through setting a custom event -> template mapping on gridControl.

```
L.mapbox.gridControl(map.gridLayer, {mapping: {
    mousemove: {
        format: 'teaser',
        popup: true,
        pin: false
    },
    click: {
        format: 'location',
        popup: true,
        pin: true
    },
    mouseout: {
        format: function() { return ''; },
        popup: false,
        pin: false
    }
}});
```

For that sort of customizability, we decided that binding directly to gridLayer events provided a better API than a complex multi-level configuration object:

```
map.gridLayer.on('click', function(data) {
    window.location.href = data.url;
});
```

As a result we hard-coded mouseover -> teaser and click -> full.

We can certainly create a single-purpose gridControl option to have click events trigger navigation rather than displaying the "full" template. Is that the use case that MapBox.com needs?

**Comment by jfirebaugh** [comment]
Add an example for the event binding in fb42ab61fb0d5555ca2724c8e6ae04f62dbbd288.

**Comment by tmcw** [comment]
Hm, this example is not really 100% there - the location formatter is a formatter and these examples just show how to do this with expected data structures.
