### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by yoannisj** [mapbox/mapbox.js#351]
I've read the doc provided at http://mapbox.com/mapbox.js/api/v1.0.0/ and spotted some errors. 

Details : https://docs.google.com/document/d/1dzYwl0THxeYikPn1NXy8d417yT4kCSJ4sIchl8ITcFw/edit?usp=sharing

Additionnaly, I've noticed the link to the mapboxjs examples on http://mapbox.com/developers/ still points to the v0.6.7 examples page

**Comment by tmcw** [comment]
The content of that doc:

---

 Topic: L.mapbox.markerLayer()

The doc says the options object provided as the second argument can take an additional property but that property is not listed/explained (looks like it has been omitted).

Topic : markerLayer.loadID()

Minor error: says “load tiles from a map with the given id on Mapbox”. Should this be “load GeoJSON data from a map with the given id on Mapbox” ?

Topic: geocoder.reverseQuery()

Explanation for first argument (“the first argument can also be an array of...”) breaks the arguments list. This markup error is particularly confusing in this case.

This is a minor issue but markup for argument lists is inconsistent (sometimes it is an ordered list and sometimes it is an unordered list). I think the most comprehensible solution is to use ordered lists for arguments and nested unordered lists for their possible formats.

The following topics show some confusing markup errors/inconsistencies :

L.mapbox.geocoder() : Argument formats in the same list as arguments themselves
L.mapbox.legendControl() : Arguments are not presented in the topic’s title
L.mapbox.gridControl() : Arguments are not presented in the topic’s title
L.mapbox.geocoderControl() : Argument formats in the same list as arguments themselves
L.mapbox.marker.style(): Arguments separated by a pipe ( | ) instead of a comma in the topic’s title

I hope these comments can help improving the mapbox.js project.
