### ISSUE TITLE
Better default control styles

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#364]
The default styles for controls should be better. Here's what they look like now:
![screen shot 2013-04-29 at 9 14 47 pm](https://f.cloud.github.com/assets/108094/442018/68578a74-b133-11e2-8a54-f1636c89b369.png)

Here's what they should look like: 

![screen shot 2013-04-29 at 9 15 46 pm](https://f.cloud.github.com/assets/108094/442030/de791150-b133-11e2-8b43-3a642bf66247.png)

(yes that's just a screenshot from tiles.mapbox.com)

Notes:
- Use data URI or SVG for icons instead of a font. Fonts look blurry. 
- Fix border radius. I would do this by setting a border radius on `.leaflet-bar` and also setting `overflow:hidden` on the bar, then removing border radius from items inside that container, like `leaflet-control-zoom-in` and `leaflet-control-zoom-out`, which currently both have border radiuses set.

**Comment by jfirebaugh** [comment]
Are you sure you are not overriding the leaflet defaults? Here is what the zoom control looks like for me, from http://mapbox.com/mapbox.js/example/v1.0.0/external-layers/.

![image](https://f.cloud.github.com/assets/98601/442047/7676e3c4-b134-11e2-984a-0ca47a4c6c65.png)

Other than being vertically oriented instead of horizontally, it looks almost identical to your tiles.mapbox.com screenshot.

**Comment by jfirebaugh** [comment]
Hmm, I guess we've modified the styles there already, never mind.

**Comment by heyitsgarrett** [comment]
I built some custom CSS that stripped Leaflet's drop shadows, etc to create a more simplified style. I can push fixes to the mismatched border-radii.

@samanpwbb - I don't understand why fonts would appear blurry for you? They theoretically render the same as an SVG would (percentage-based rendering).

**Comment by samanpwbb** [comment]
@heyitsgarrett Using a standard font for icons like this will never result in crisp edges, where everything is properly aligned to the pixel grid. I am not using a retina monitor so they look blurry.

@jfirebaugh yeah, I just overrode those on the MapBox site :P

**Comment by samanpwbb** [comment]
In order to get styles I wanted, I needed to do this: https://gist.github.com/samanpwbb/5490008

Some realizations:
- We should cancel out all the `.leaflet-touch` styles. There are much better ways to set custom styles for mobile.
- There are instances of things like `border-bottom:0` and `background:#foo` that should be replaced with `background-color:#foo` and `border-bottom-width:0` so they're easier to override.
- Border radius should only ever be applied to one element in a situation which stacked elements, either parent or child, not both.

**Comment by heyitsgarrett** [comment]
I'm rather against the idea of sprites in mapbox.js library for two reasons:
- Another dependency to maintain, support, edit when people host mapbox.js themselves
- It's an additional http request

If the `+` and `-` is bothersome to that degree, I'd be okay with an SVG, although even after looking at a non-retina monitor I think the usage of fonts a minor detail.

The points on `background-color`, `border-bottom`, etc _are_ bothersome and I can adjust those on our end.

Regarding overriding `.leaflet-touch`, we should push this farther upstream to Leaflet itself rather than having `mapbox.js` serve as a bandaid.

**Comment by samanpwbb** [comment]
@heyitsgarrett for the icons, how about an SVG embed in CSS with a fallback with a data uri'd PNG? This can all just live in the CSS with no external files.

**Comment by heyitsgarrett** [comment]
@samanpwbb - Sure, under the condition that it doesn't bloat filesize to an unbecoming degree, I can get behind this.

**Comment by samanpwbb** [comment]
As we're working on porting tiles.mapbox.com over to the latest mapbox.js, now would be a good time to fix this. cc: @heyitsgarrett

**Comment by tristen** [comment]
Captured in master and will be released in the next `v1.4.1` + versions
