### ISSUE TITLE
Can't set maxZoom

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#371]
This example demonstrates how you can't set a ZL > 18 on mapbox.js

https://gist.github.com/lxbarth/8823aca9f5b6faea1ef4

**Comment by jfirebaugh** [comment]
What exactly doesn't work? It looks like it's working to me with v1 final.

**Comment by lxbarth** [comment]
Upgraded to final and can't go deeper than ZL 18: http://bl.ocks.org/lxbarth/8823aca9f5b6faea1ef4

**Comment by jfirebaugh** [comment]
Leaflet [defines](https://github.com/Leaflet/Leaflet/blob/e032046119a7f60d0a798472e49e283a29e502da/src/map/Map.js#L334-L339) maxZoom as the minimum of the map maxZoom and the layers' maxZooms. The tile layer has a max zoom of 19, so that becomes the effective maximum. If you want to override what the TileJSON says is the maximum, you'll need to construct a tile layer manually.

**Comment by patrickhill** [comment]
Thanks lxbarth, the code sample fixed the issue for me!
