### ISSUE TITLE
Include Leaflet documentation on mapbox.com/mapbox.js

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox.js#446]
I think people often forget or don't read the documentation that mapbox.js is based on Leaflet. Because of this, people can't find the answer to simple questions. Although the page would be gigantic, I think it might be worth while to have all the documentation about MapBox.js in one place instead of across two websites.

Just a thought.

cc @jfirebaugh @tmcw

**Comment by tmcw** [comment]
Er, yeah.. see previous #281 

Pulling in all Leaflet documentation would be a bit crazy, especially since they're managed in vastly different ways (markdown vs html, different strategies for linking, examples, and structure).

We should point to leaflet better and communicate about it better, though. We need to weigh that against the reality that the tl;dr users will never ever read regardless.

**Comment by jfirebaugh** [comment]
Done!
