### ISSUE TITLE
'ready' event not firing in Internet Explorer

### ISSUE THREAD

**Issue by om-henners** [mapbox/mapbox.js#472]
Hi guys,

Doing some development on 1.3.1 and it appears that the layer 'ready' event is not being fired in IE 8, 9 and 10.

```
layer.on('ready', function(){
    alert("This shows up in Firefox and Chrome, but not IE");
});
layer.on('load', function(){
    alert("This shows up everywhere");
});
```

mapbox.js 1.3.1, Firefox 22.0, Internet Explorer 10.0.9200.16635, Chrome 28.0.1500.72 m

**Comment by jfirebaugh** [comment]
Usually this is caused by a race condition in your code, i.e. binding to the `ready` event when it might have already been dispatched. Can you post your code?

**Comment by om-henners** [comment]
No worries. Sorry for the delay in getting back to this. The ActivateMap function is called on the page initialisation with the mapbox ID of the map we want to load. It's also called if we want to switch maps.



```
ActivateMap = function(map, mapbox_id){
    //create a new layer
    var layer = L.mapbox.tileLayer(mapbox_id);
    var SelectedLayer = layer;

    /*
     * this is a workaround for an issue where IE doesnt fire
     * the ready event, load is triggered after any map tile is loaded.
     */
    layer.on('load', function(){
        var meta = layer.getTileJSON();
        NavigateHome(map, meta); //navigates to map origin
        }
    });

    // this is triggered once when the layer is loaded, this works for firefox + chrome
    layer.on('ready', function(){        
        var meta = layer.getTileJSON();
        NavigateHome(map, meta); //navigates to map origin
    });

    map.addLayer(layer);
}
```

**Comment by jfirebaugh** [comment]
Thanks, I was able to reproduce the problem in IE. It does come down to a race condition that is at root due to quirk of IE's XDomainRequest implementation, but it's one that MapBox.js should be working around internally so that the code you wrote works. I'm working on a fix, but in the meantime, your workaround should work. Just make sure you turn off the 'load' event binding after the first event, so it doesn't keep navigating home whenever a new tile is loaded.
