### ISSUE TITLE
Build marker visuals with CSS not images 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#593]
Markers/data made with the mapbox.com editor should be built with CSS + classes not with images. Right now, each marker is basically a link to a URL that defines the color, size, and icon. Markers should be more like this:

``` html
<div class='size-medium color-pink marker'>
    <span class='icon alcohol-shop'></span>
</div>
```

rather than 

``` html
<img src='https://a.tiles.mapbox.com/v3/marker/pin-m+f56098.png' class='marker' />
```

Why? 
- To make it more clear to our designer/dev audience that it's possible to mess with the style of markers with their own CSS and classes. How to replace and style markers from Mapbox is not clear right now unless you're a developer who has a pretty deep understanding of how things work.
- To relieve us of the burden of maintaining and modifying the marker background images. These can easily be reconstructed with CSS. It also opens up more options in the UI, like adding a variety of shapes or animation behaviors to markers just by swapping classes.

@tmcw / @mourner what steps do we need to take to make this happen?

**Comment by tmcw** [comment]
Can you do a quick demo for that this might look like? For my long-term plans I'm more interested in Canvas-rendered markers like [skycons](http://darkskyapp.github.io/skycons/) - see [localmarker](http://macwright.org/local-marker/) for a demo of that. The 'why' is so that we can still do arbitrary any-color-combinations and also simply implement this for canvas compositing and node-canvas.

**Comment by mourner** [comment]
Yeah, the markers are pretty simple so they could be reconstructed using pure CSS easily, the only serious drawback (and the main reason why I chose `img` tag in the first place) being that browsers don't print CSS backgrounds (perhaps we could hack a fallback for this). But I like the idea of combining classes and using CSS transitions to animate between different marker states/shapes/colors.

On the Leaflet side, it's pretty easy to implement — just use [DivIcon](http://leafletjs.com/reference.html#divicon) instead of Icon.

Canvas icons is also a good idea and Tom's demo is very nice. Pros — no problems with printing, more flexible. Cons — you can't do easing between different icons like with CSS transitions/animations.

**Comment by tmcw** [comment]
Fwiw, though easing/transitions aren't built in, they'd be simple to implement efficiently

**Comment by samanpwbb** [comment]
I will sketch some things out. 

Another goal here is to avoid inline styling as much as possible. This could get weird. Obviously if we have freeform hex value inputs for marker colors we're going to need to do inline styles, but it'd be interesting to try to avoid all inline styles as possible to make styles easier for designers to override.

**Comment by mourner** [comment]
@tmcw for things like color transitions, yes, but not so easy for transitions between different shapes I guess.
