### ISSUE TITLE
MakerLayer's filter causes unexpected issues

### ISSUE THREAD

**Issue by asolove** [mapbox/mapbox.js#604]
There seem to be a few issues where changing the filter of a MarkerLayer causes it to behave unexpectedly. For example, if I create, filter, and style a layer with geojson:

``` javascript
layer = L.mapbox.markerLayer(data).addTo(map);
layer.setFilter(filterBySomething);
layer.setStyle(myStyle);

// and later change the filter:
layer.setFilter(filterBySomethingElse);
```

Any features that are newly-visible under the new filter will not have the style set earlier.

It seems like this will be a problem with any `MarkerLayer` methods inherited from Leaflet's `FeatureGroup` that use `invoke`, since `invoke` iterates over the layers known about on the Leaflet level (only the ones that pass the filter) and not the ones filtered out on the `MarkerLayer` level.

Possible solutions:
- My particular problem with `setStyle` can be fixed by having `setFilter` call `setStyle` manually, but that leaves other potential problems. 
- Perhaps `MarkerLayer` should define its own version of `invoke` that iterates over all the layers, even the ones currently filtered out.

**Comment by tmcw** [comment]
Looks like expected behavior to me: `setFilter` is internally a reset, and `setStyle` says 'set style now' and does not [set styles of new features in GeoJSON layers](http://bl.ocks.org/tmcw/7998444). If you want persistent styles, it'd be better to use `layeradd`, `pointToLayer`, or `onEachFeature` - functions that have a contract of styling all future additions as well as features-right-now.

**Comment by asolove** [comment]
Hmm, ok, I guess my mental model of what the filter means was incorrect.
