### ISSUE TITLE
AMD Compliance

### ISSUE THREAD

**Issue by TylerBre** [mapbox/mapbox.js#674]
Would it be possible to de-couple mapbox.js from npm modules/browserify? Not suggesting a massive re-write, but this is useless to anyone not using npm/browserify.

**Comment by tmcw** [comment]
Could you go into a little more detail about this is useless without browserify, and how the existing AMD wrapper isn't doing it for you?

**Comment by TylerBre** [comment]
I didn't realize you included a shim or wrapper for AMD. If you did, where is this located?

But, I think the AMD issue could easily be mitigated by just including the compiled script in a dist folder.

**Comment by tmcw** [comment]
The shim is included by [the browserify standalone option](https://github.com/substack/node-browserify#usage).

We are not going to check dist files into git, but in the future we do plan to push `zip` downloads around: that's covered by #567 and since we already do AMD, closing here.

**Comment by Rich-Harris** [comment]
@tmcw Is there a reason not to use the `browserify --standalone` build as the default (i.e. instead of http://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js)? I just spent a deeply frustrating morning trying to get mapbox to work in an AMD project.

If there _is_ some reason not to serve that as the default build, then can I kindly suggest some larger signposting on how to use mapbox with AMD? You say 'since we already do AMD' but it's not clear what you mean by that.

For anyone finding this thread via Google: these are the steps I took to create a build that I could use:
- clone this repo
- install browserify if you haven't already (`npm install -g browserify`)
- `cd` into the `mapbox.js` folder containing this repo
- do `browserify index.js -o mapbox.amd.js --standalone mapbox`

You still won't be able to use mapbox as an AMD module, but you can at least then do

``` js
define( function ( require ) {
  require( 'mapbox.amd' );
  var L = window.L; // Leaflet gets attached to the global namespace

  var map = L.mapbox.map(...);
});
```

If I've misunderstood and there's a better way, I'd appreciate any guidance. Thanks

**Comment by tmcw** [comment]
>  Is there a reason not to use the browserify --standalone build as the default (i.e. instead of http://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js)?

Mapbox exports itself as L.mapbox, and does not overwrite L. Browserify standalone expects a root-level variable name and doesn't handle 'attach this code to an existing object' as one of its cases, understandably.

I've edited out your `?!`: your frustration is registered. When we find a better way to do AMD for modules that use modules, we'll use it, but for the time being it doesn't seem like it's the greatest system for this kind of thing. You're welcome to maintain a `mapbox.js-amd` wrapper that does things another way.

**Comment by Rich-Harris** [comment]
Yeah, I hear what you say about AMD not being ideal for modules that use modules. Browserify and the r.js optimiser don't play at all nicely together, unfortunately. I had a go at creating a `mapbox.amd.js` wrapper...

``` js
define([ 'leaflet' ], function ( L ) {
  L.Icon.Default.imagePath = '//api.tiles.mapbox.com/mapbox.js/' + 'v' +
    require('./package.json').version + '/images';
  L.mapbox = {
    ...
  };
  L.mapbox.markerLayer = L.mapbox.featureLayer;
  return L.mapbox;
});
```

...but while that works fine in development, it falls apart when you build it because some of mapbox's dependencies do `define()` calls of their own, which r.js can't cope with. It's a shame because resolving dependencies at runtime is exactly where AMD excels.

The solution I eventually settled on is this: https://github.com/Rich-Harris/leaflet.mapbox.js/blob/master/leaflet.mapbox.js. Basically no different from the `--standalone` build, except that it exports `L` - so you can use it the same way as you'd use the version you serve from the CDN but also do

``` js
define( function ( require ) {
  var L = require( 'leaflet.mapbox' );
  var map = L.mapbox.map(...);
});
```

But I digress - my point was that it was really hard to figure out how to use mapbox with AMD at all, to the point where I almost gave up (I don't have a choice about AMD, and it's not possible to just drop in a script tag pointing to the CDN), and it would be really helpful if there were clearer directions for people in a similar situation. Cheers
