### ISSUE TITLE
How can i custom omnivore line (using gpx file)?

### ISSUE THREAD

**Issue by jdirand** [mapbox/mapbox.js#727]
Hi,
I'm using omnivore to load a gpx file.
It draws a blue itinerary, and i would like to custom this line.
Is it possible?

Thanks a lot,

J.

**Comment by tmcw** [comment]
See the [imported data with custom marker styles example](https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-from-csv-custom-style/), and it's the same technique: use the `on` event in order to wait until data is loaded, and then style it just as you'd style any other L.geoJson layer, in this case with [.setStyle](http://leafletjs.com/reference.html#path-setstyle).
