### ISSUE TITLE
Cannot read property 'replace' of undefined after panning

### ISSUE THREAD

**Issue by cperryk** [mapbox/mapbox.js#737]
I'm having trouble understanding why this isn't working.

Go to this map:

http://slate.slategrouptech.com/interactives/agingMapLite/

Click and drag the map, traveling West. Do it a few times, and you'll see this error pop up in the javascript console, and the map will simply stop working:

```
Uncaught TypeError: Cannot read property 'replace' of undefined mapbox.js:1
s.Util.template mapbox.js:1
L.Class.extend._getTileURL mapbox.js:6
L.Class.extend._getTile mapbox.js:6
L.Class.extend._update mapbox.js:6
s.Mixin.Events.fireEvent mapbox.js:1
s.Map.Drag.s.Handler.extend._onDragEnd mapbox.js:4
s.Mixin.Events.fireEvent mapbox.js:1
s.Draggable.s.Class.extend._onUp mapbox.js:4
t.(anonymous function).o
```

This seems to happen after dragging past 0 longitude twice.

Strangely, it doesn't happen going East.

I'm completely stumped by this.

**Comment by jfirebaugh** [comment]
Hi @cperryk. This looks like a bug in mapbox.js. We'll fix it for the next version. In the meantime, I think you can work around it by setting the `worldCopyJump` option of the map to `true`:

```
  var map = L.mapbox.map('map','slate.k8i79zfr', {worldCopyJump: true}).setView([40, 20.50], 2);
```

**Comment by cperryk** [comment]
Thanks, that did the trick!

**Comment by jfirebaugh** [comment]
Great! I'm going to keep this open so we can track fixing this in mapbox.js.

**Comment by tmcw** [comment]
Relevant section of code: https://github.com/mapbox/mapbox.js/blob/787849a95e8c61923e78adce83bf614860f944a7/src/tile_layer.js#L82-94

Not immediately seeing how this could crop up, any idea @jfirebaugh ?

**Comment by jfirebaugh** [comment]
This comes from grid_layer.js rather than tile_layer.js: https://github.com/mapbox/mapbox.js/blob/787849a95e8c61923e78adce83bf614860f944a7/src/grid_layer.js#L131-L135

When this happens, the `tilePoint.x` is -1, which is the result of the math [here](https://github.com/mapbox/mapbox.js/blob/787849a95e8c61923e78adce83bf614860f944a7/src/grid_layer.js#L148-L162). Not sure if -1 is a valid value and needs to be handled or if the math is wrong.

[Fiddle](http://jsfiddle.net/Cvvfu/1/) (pan to the left until you get the error)
