### ISSUE TITLE
layer switching breaks "improve map" link

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#929]
It looks like the [edit link](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/map.js#L135-L150) function is not called when the map layer is updated on the page (via a layer switcher) or when using `L.control.layers`.

To demonstrate, open https://www.mapbox.com/mapbox.js/example/v1.0.0/layers-control/  switch the map layer and select, _Improve this map_. The coordinates nor MapID is passed to https://mapbox.com/map-feedback/

If the following sounds like a good course of action, I'd like to:
1. Pull [`_editLink](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/map.js#L135-L150) out of map.js and add it to [util.js](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/util.js)
2. Call it from [`grid_layer.js`](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/grid_layer.js), [`feature_layer.js`](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/feature_layer.js), & [`tile_layer.js`](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/tile_layer.js) respectively.

cc/ @tmcw @jfirebaugh

**Comment by jfirebaugh** [comment]
That doesn't sound like the right fix to me. Why is `_editLink` not being called when the map layer is updated on the page? Is it because the layer has already emitted a `ready` event and `_updateLayer` doesn't get called [here](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/map.js#L85)? If so, the right fix is to change the code there to bind to the `ready` event (if the layer is not yet ready) _or_ call `_updateLayer` immediately (if it is ready). That way all the other stuff that `_updateLayer` needs to do will get taken care of too.

Also, it looks like there's bug currently that will cause `this._editLink` to be called once per layer on `moveend`, because an additional binding is added every time `_updateLayer` is called. The event should be bound once, in `_initialize`, and `_updateLayer` should just call `_editLink` directly (which it already does).

**Comment by lxbarth** [comment]
This is still broken at least in some cases.

Take a look at http://lxbarth.com/map/ - the "improve map" link does not pass on a map id where it should. I'm using the latest mapbox.js (built from mb-pages just now). I could track down the issue to `this._tilejson` empty in `_updateMapFeedbackLink` https://github.com/mapbox/mapbox.js/blob/mb-pages/src/map.js#L173 - not sure why it does not wind up being set before.

I set up the layers like this: https://github.com/lxbarth/map/blob/gh-pages/index.html#L65

**Comment by jfirebaugh** [comment]
Opening a clean ticket for this case: #953.
