### ISSUE TITLE
Unknown runtime error - Internet Explorer 8

### ISSUE THREAD

**Issue by aaani** [mapbox/mapbox.js#957]
I am getting this error in mapbox.js v2.1.5 and v1.6.4
![image](https://cloud.githubusercontent.com/assets/3347504/6331034/cddb568c-bb4a-11e4-88c2-30a8011a9a5f.png)

from this line of code in IE 8

<pre>this.options.prefix&&i.push(this.options.prefix),t.length&&i.push(t.join(",")),this._container.innerHTML=i.join(" | ")</pre>

Possible fix: http://stackoverflow.com/questions/7892102/fixing-unknown-runtime-error-in-ie8

Is there any workaround to suppress this error?

**Comment by tmcw** [comment]
Can you give a live example of this error, in a jsfiddle or standalone html page?

**Comment by aaani** [comment]
http://jsbin.com/pokeqatuso/1/#/map does this help? This page has a script that loads mapbox.js and initializes the map.

**Comment by aaani** [comment]
Any updates about this?

**Comment by jfirebaugh** [comment]
Hi @aaani. This error occurs in Leaflet when setting the map attribution. I don't see any problem with the code there, and this same code works on IE 8 in other context such as Mapbox map embeds. I think this must be triggered by something specific to your site. Your best bet is to try to reduce your test case to something smaller and more self contained, to narrow down what it is that's causing the issue.

Closing here since I don't think there's a bug in Mapbox.js. However if you can create a simpler example that still demonstrates the issue I can take another look.
