### ISSUE TITLE
Tiles caching and compression

### ISSUE THREAD

**Issue by aaani** [mapbox/mapbox.js#977]
When I audit a mapbox powered map using Google page insights tool (https://developers.google.com/speed/pagespeed/insights) I get multiple issues due to low cache time of tiles:
![image](https://cloud.githubusercontent.com/assets/3347504/6721703/07e38aec-cd9e-11e4-9b01-f9c2da81b68f.png)

and uncompressed tiles:
![image](https://cloud.githubusercontent.com/assets/3347504/6721710/19541efe-cd9e-11e4-81e6-5da4486c0070.png)

Is there any way to set high cache time and get compressed images? I tried to change the image format to jpg70 but still got the same issues in the audit. Any workaround to suppress these issues in the report would also be helpful. Thanks!

Audit link: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.mapbox.com%2Fmapbox.js%2Fexample%2Fv1.0.0%2F&tab=desktop

**Comment by tmcw** [comment]
This is outside the scope of Mapbox.js: Mapbox.js is a client to Mapbox.com and has no control over tile caching or compression options. Feel free to contact support@mapbox.com for issues with Mapbox's API service, but since this issue can't be fixed from the Mapbox.js side I'll need to close it because no commit could.
