### ISSUE TITLE
Canonical method for adding a custom image marker to a map

### ISSUE THREAD

**Issue by barneycarroll** [mapbox/mapbox.js#994]
Hi guys, I've been crawling back and forth in the documentation but seem to be getting more and more confused.

I have my own set of images to represent various points. I have tried using markers (including icons) and features (code below the post and in [this fiddle](http://jsfiddle.net/barney/n4zjc6hz/)). The problem I have with markers is that they seem to interpret latlng differently; the problem I have with features is that I can't find a complete documentation of what properties they support. If anybody could help me achieve both accurate positioning and custom imagery using a single consistent API, I'd be much obliged.

``` javascript
L.mapbox.accessToken = 'xxx';

L.mapbox
    .map( document.body, 'examples.map-i86nkdio' )
    .locate()
    .on( 'locationfound', function( e ){
        this.fitWorld();

        L.marker( [
            e.latlng.lng,
            e.latlng.lat
        ], {
            icon : L.icon( {
                iconUrl : 'http://lorempixel.com/64/64/',
            } )
        } ).addTo( this );

        L.mapbox.featureLayer( {
            type      : 'Feature',
            geometry  : {
                type        : 'Point',
                coordinates : [
                    e.latlng.lng,
                    e.latlng.lat
                ]
            },
            properties : {
                iconUrl : 'http://lorempixel.com/64/64/'
            }
        } ).addTo( this );
    } );
```

**Comment by jfirebaugh** [comment]
Hi @barneycarroll! Coordinate order is a common point of confusion. `L.marker` uses lat, lng order, so you can pass `e.latlng` directly:

```
    L.marker(e.latlng, {
        icon : L.icon( {
            iconUrl : 'http://lorempixel.com/64/64/',
        } )
    } ).addTo( this );
```

GeoJSON uses lng, lat though. Your code uses the correct coordinate order there. To get custom marker images with a `L.mapbox.featureLayer`, you'll need to hook up a `'layeradd'` event -- see [this example](https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker/).

**Comment by barneycarroll** [comment]
Aha! Thanks @jfirebaugh. So I'm better off using GeoJSON features API and then invoking Leaflet API after initialisation to initialise proper Leaflet classes using a Leaflet API that's dimly aware of the GeoJSON content?

TBH I find that demo incredibly confusing. The reasoning behind invocation of the various API hooks doesn't make much sense to me:
- The layer is added to the map synchronously [here](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L15)
- After the synchronous `addTo` invocation, a `layeradd` event handler is [registered](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L52).
- After the layer is added to the map, the GeoJSON is defined, and the handler is registered, the [GeoJSON is added to the layer](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L52).

I find it impossible to construct a mental model of the sequence of events based on the code for this seemingly simple task.

In particular:
- Why is `setGeoJSON` invoked after the layer is added to the map, when the content of the GeoJSON is known ahead of time, and the layer constructor accepts GeoJSON on initialisation?
- Variation on the above: why do the examples almost always combine a variable assignment with the chained call to `addTo( map )` only to use other chained method calls (that could have been part of initialisation) at some arbitrary later stage?
- Why is the `layeradd` event asynchronous, and why do I need new references from the event object to perform actions which were implicit in the options passed in earlier?
- What's the point of using an estoeric DSL with different conventions (ie latlng / lnglat ) to define my content if I need to use a different API to reference that DSL and initialise my simple, static element later on anyway?

**Comment by jfirebaugh** [comment]
@barneycarroll Good questions.

The reason why you can't pass the GeoJSON directly to the `L.mapbox.featureLayer` constructor is that the constructor acts synchronously when passed a GeoJSON object literal. It will add the features to the layer immediately, before the `layeradd` event handler is registered, and the event callback will never be called.

In this example, there is in fact no asynchronicity. The `layeradd` events are dispatched synchronously, as part of the call to `setGeoJSON`.

I'm not sure what you mean by "new references from the event object to perform actions which were implicit in the options passed in earlier". It sounds like you might be expecting the [`icon` property](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L25-L31) alone to produce custom icons. This confusion is understandable, but it isn't how `L.mapbox.featureLayer` works. The GeoJSON properties that `L.mapbox.featureLayer` handles for you automatically are those defined in the [simplestyle spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0), and custom marker images aren't a part of that specification -- that's why `layeradd` is necessary.

**Comment by barneycarroll** [comment]
Thanks, I'm learning a lot through this :)

> In this example, there is in fact no asynchronicity

I was wondering if the `layeradd` function needed to exist in case some advanced logic in `featureLayer` initialisation might determine that async options were necessary. If there is in fact nothing async going on, I really don't understand why the code is written the way it is. Maybe it's constructed from snippets from a larger application which did have async requirements?

> I'm not sure what you mean by "new references from the event object to perform actions which were implicit in the options passed in earlier".

Well, we've already got distinct references to [`geoJson`](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L17)(which seems pointless, since the object could have been passed in to the `featureLayer` constructor directly) and [`myLayer`](https://github.com/mapbox/mapbox.js/blob/8fef4a0f35f18343016b29f0eee8f4713ae4d5bb/docs/_posts/examples/v1.0.0/0100-01-01-custom-marker.html#L15)(which seems pointless, since in the assignment we are already making use of the fluent API by immediately invoking `addTo( map )` – there's no reason we couldn't have bound the event listener and bound the GeoJSON in the same chain). But despite already having these otherwise redundant references, and no callbacks being necessary since all the initialisation and configuration operations are synchronous, we still need to retrieve our reference to the icon definition _and_ the layer through the event object passed to the callback. Is that really necessary?

**Comment by jfirebaugh** [comment]
This won't work:

```
L.mapbox.featureLayer({ /* geojson here */ })
  .on('layeradd', function(e) {
    var marker = e.layer,
        feature = marker.feature;
    marker.setIcon(L.icon(feature.properties.icon))
  })
  .addTo(map);
```

This is a fluent API, but it doesn't make anything asynchronous; each thing still happens as soon as you call a method. So first `L.mapbox.featureLayer(geoJson)` is called, which does `setGeoJSON` internally, and all the GeoJSON is converted to layers and added. Then `.on('layeradd', ...)` is called, and the event handler is registered. But it never gets called, because the GeoJSON has already been added.

You could write the example like this:

```
L.mapbox.featureLayer()
  .on('layeradd', function(e) {
    var marker = e.layer,
        feature = marker.feature;
    marker.setIcon(L.icon(feature.properties.icon))
  })
  .setGeoJSON({ /* geojson here */ })
  .addTo(map);
```

But with the actual large block of GeoJSON and explanatory comments that comes out less readable than the existing code in my opinion.

**Comment by barneycarroll** [comment]
Why are we using callbacks at all?

**Comment by barneycarroll** [comment]
I've forked my fiddle to show my attempt at finding a simple way of adding a marker with a custom image using the different APIs. Using Markers directly looks far better to me. AFAICT the only reason the FeatureLayer API uses events is to expose the marker object, which is otherwise private – based on the example, the FeatureLayer API looks horrific. I've worked out the `layeradd` event is just a hack to expose the generated Marker via the event object, which would otherwise be inaccessible.

Also, is it worth submitting a PR for the example?
